import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ReactQueryClientProvider } from "@/providers/ReactQueryClientProvider";
import { Toaster } from "sonner";
import Providers from "@/providers/Providers";
import Navbar from "@/components/Frontend/Navbar";
import MegaMenu from "@/components/Frontend/MegaMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <div className="bg-white">
              <Navbar />
              <div className="container">
                <div className="bg-white mx-auto py-4 fixed top-20 w-full left-0 z-50 right-0 border-t border-gray-400/30">
                  <MegaMenu />
                </div>
              </div>
              <main>{children}</main>
            </div>
            <Toaster
              richColors
              position="top-right"
              closeButton
              duration={5000}
            />
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
