export const facultyData = [
  { id: 1, name: "Tim mạch", description: "Chuyên khoa về tim và hệ tuần hoàn." },
  { id: 2, name: "Thần kinh", description: "Tập trung vào các rối loạn của hệ thần kinh." },
  { id: 3, name: "Chấn thương chỉnh hình", description: "Điều trị các vấn đề về hệ cơ xương." },
  { id: 4, name: "Da liễu", description: "Chuyên khoa về các bệnh lý liên quan đến da." },
  { id: 5, name: "Nhi khoa", description: "Chuyên về chăm sóc sức khỏe cho trẻ em." },
  { id: 6, name: "Nội tiết", description: "Chuyên khoa về hormone và các rối loạn nội tiết." },
  { id: 7, name: "Hô hấp", description: "Chuyên khoa điều trị các bệnh về phổi và hô hấp." },
  { id: 8, name: "Tâm thần", description: "Chăm sóc sức khỏe tâm thần và các rối loạn tâm lý." },
  { id: 9, name: "Tiêu hóa", description: "Điều trị các vấn đề liên quan đến hệ tiêu hóa." },
  { id: 10, name: "Phụ khoa", description: "Chuyên khoa về sức khỏe phụ nữ và các vấn đề sinh sản." },
  { id: 11, name: "Mắt", description: "Chăm sóc và điều trị các bệnh về mắt." },
  { id: 12, name: "Răng hàm mặt", description: "Chuyên về sức khỏe răng miệng và phẫu thuật hàm mặt." },
  { id: 13, name: "Ngoại khoa", description: "Chuyên về phẫu thuật và điều trị ngoại khoa." },
  { id: 14, name: "Y học cổ truyền", description: "Chuyên khoa về các phương pháp điều trị cổ truyền." },
  { id: 15, name: "Xét nghiệm", description: "Phân tích và đánh giá các chỉ số sức khỏe." },
  { id: 16, name: "Chấn thương", description: "Chuyên khoa về điều trị chấn thương thể chất." },
  { id: 17, name: "Huyết học", description: "Nghiên cứu và điều trị các bệnh lý về máu." },
  { id: 18, name: "Tâm lý học", description: "Nghiên cứu và điều trị các vấn đề tâm lý." },
  { id: 19, name: "Chăm sóc sức khỏe", description: "Chuyên về quản lý sức khỏe tổng quát." },
  { id: 20, name: "Dinh dưỡng", description: "Chuyên khoa về chế độ ăn uống và dinh dưỡng." },
];
