// LOGIN & REGISTER
export const INPUT_REQUIRED = 'Trường này là bắt buộc'
export const NAME_LENGTH = 'Tên phải ít nhất 6 kí tự'
export const INVALID_EMAIL = 'Email không hợp lệ'
export const PASSWORD_LENGTH = 'Mật khẩu phải chứa 6 kí tự'
export const INCORRECT_PASSWORD = 'Mật khẩu không trùng khớp'
export const MIN_LENGTH_PHONE = 'Số điện thoại phải có ít nhất 10 chữ số'
export const MAX_lENGTH_PHONE = 'Số điện thoại không quá 11 chữ số'
export const CREATE_ACCOUNT_SUCCESS = 'Tạo tài khoản thành công'
export const CREATE_ACCOUNT_FAIL = 'Tạo tài khoản thất bại'
export const PASSWORD_REQUIRED = 'Yêu cầu mật khẩu'
export const LOGIN_REQUIRED = 'Vui lòng đăng nhập'
export const AVATAR_REQUIRED = 'Yêu cầu chọn ảnh dành cho tài khoản'
