export const INPUT_REQUIRED = 'Trường này là bắt buộc'
export const NAME_DOCTOR_LENGTH = 'Tên bác sĩ không được quá 50 ký tự'
export const INVALID_SPECIAL_CHARACTER = 'Tên không được nhập ký tự đặc biệt'
export const IMAGE_DOCTOR_REQUIRED = 'Vui lòng chọn ảnh bác sĩ'
export const ACADEMICTITLE_REQUIRED = 'Vui lòng chọn học hàm/học vị bác sĩ'
export const FACULTY_REQUIRED = 'Vui lòng chọn chuyên khoa'
export const DESCRIPTION_LENGTH = 'Mô tả chỉ được phép tối đa 500 ký tự.'
export const INVALID_IMAGE_DOCTOR = 'Vui lòng chọn file ảnh hợp lệ (JPEG, PNG).'
