export const COMMENT_NOT_FOUND = 'Không tìm thấy đánh giá'
export const FAILED_GET_COMMENT = 'Lỗi khi lấy thông tin đánh giá'
export const FAILED_DELETE_COMMENT = 'Lỗi khi xóa đánh giá'
export const SUCCESS_DELETE_COMMENT = 'Xóa đánh giá thành công'
export const FAILED_DELETE_COMMENT_AGAIN = 'Bạn đã đánh giá cuộc hẹn này với bác sĩ rồi'
