export const PROFILE_NOT_FOUND = 'Không tìm thấy hồ sơ bệnh nhân'
export const UNAUTHENTICATED = 'Yêu cầu đăng nhập'
export const FAILED_GET_PROFILE = 'Lỗi khi lấy dữ liệu hồ sơ bệnh nhân'
export const FAILED_GET_PROFILES = 'Lỗi khi lấy danh sách hồ sơ bệnh nhân'
export const SUCCESS_CREATE_PROFILE = 'Tạo hồ sơ bệnh nhân thành công'
export const SUCCESS_UPDATE_PROFILE = 'Cập nhật hồ sơ bệnh nhân thành công'
export const SUCCESS_DELETE_PROFILE = 'Xóa hồ sơ bệnh nhân thành công'
export const FAILED_CREATE_PROFILE = 'Tạo hồ sơ bệnh nhân thất bại'
export const FAILED_UPDATE_PROFILE = 'Cập nhật hồ sơ bệnh nhân thất bại'
export const FAILED_DELETE_PROFILE = 'Xóa hồ sơ bệnh nhân thất bại'
export const FAILED_DELETE_PROFILE_HAS_APPOINTMENT =
  'Lỗi khi xóa hồ sơ, hồ sơ này đang có lịch hẹn.Vui lòng thử lại sau!'
export const INCORRECT_IDENTIFICATION =
  'Số giấy định danh không hợp lệ. Vui lòng kiểm tra lại.'
export const NOTICE_DELETE = 'Bạn có chắc chắn muốn xóa hồ sơ này không?'
